software:
  ncurses:
    toolchains:
      cpeAMD-22.08:
        versions: ['6.2']
  libreadline:
    toolchains:
      cpeAMD-22.08:
        versions: ['8.1.2']
  gettext:
    toolchains:
      cpeAMD-22.08:
        versions:
          '0.21':
            versionsuffix: '-minimal'
#  GSL:
#    toolchains:
#      cpeAMD-22.08:
#        versions: 
#          '2.7.1':
#            versionsuffix: '-sequential'
