software:
  Blosc:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.21.1']
  Brotli:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.0.9']
  bzip2:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.0.8']
  DB:
    toolchains:
      cpeAMD-22.08:
        versions: ['18.1.40']
  double-conversion:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.2.0']
  expat:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.4.8']
  FriBidi:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.0.12']
  giflib:
    toolchains:
      cpeAMD-22.08:
        versions: ['5.2.1']
  gc:
    toolchains:
      cpeAMD-22.08:
        versions: ['8.2.0']
#  GMP:
#    toolchains:
#      cpeAMD-22.08:
#        versions: ['6.2.1']
#  GSL:
#    toolchains:
#      cpeAMD-22.08:
#        versions: 
#          '2.7.1':
#            versionsuffix: '-OpenMP'
  gzip:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.12']
  ICU:
    toolchains:
      cpeAMD-22.08:
        versions: ['71.1']
  libaec:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.0.6']
  libb2:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.98.1']
  libcerf:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.1']
  libdeflate:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.12']
  libffi:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.4.2']
  libidn:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.38']
  libidn2:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.3.2']
  libjpeg-turbo:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.1.3']
  libogg:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.5']
  libopus:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.1']
  libpsl:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.21.1']
  libtirpc:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.2']
  libyaml:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.2.5']
  LMDB:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.9.29']
  lz4:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.9.3']
  Lzip:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.23']
  LZO:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.10']
  mpdecimal:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.5.1']
  Szip:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.1.1']
  termcap:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.1']
  x264:
    toolchains:
      cpeAMD-22.08:
        versions: ['20210613']
  x265:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.5']
  zlib:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.2.12']
  cURL:
    toolchains:
      cpeAMD-22.08:
        versions: ['7.83.1']
  FLAC:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.4']
  JasPer:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.0.4']
  LAME:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.100']
  libevent:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.1.12']
  libpciaccess:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.16']
  libpng:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.6.37']
  libvorbis:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.3.7']
#  MPFR:
#    toolchains:
#      cpeAMD-22.08:
#        versions: ['4.1.0']
  snappy:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.1.9']
  Tcl:
    toolchains:
      cpeAMD-22.08:
        versions: ['8.6.12']
  UDUNITS:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.2.28']
  freetype:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.12.1']
  libiconv:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.17']
  libsndfile:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.1.0']
  libtheora:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.1.1']
#  MPC:
#    toolchains:
#      cpeAMD-22.08:
#        versions: ['1.2.1']
  PCRE:
    toolchains:
      cpeAMD-22.08:
        versions: ['8.45']
  PCRE2:
    toolchains:
      cpeAMD-22.08:
        versions: ['10.40']
  pixman:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.40.0']
  SQLite:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.38.3']
  XZ:
    toolchains:
      cpeAMD-22.08:
        versions: ['5.2.5']
  file:
    toolchains:
      cpeAMD-22.08:
        versions: ['5.42']
  libunistring:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.0']
  libunwind:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.6.2']
  libxml2:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.9.12']
  wget:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.21.3']
  zstd:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.5.2']
  Boost:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.79.0']
  libarchive:
    toolchains:
      cpeAMD-22.08:
        versions: ['3.6.1']
  gettext: # The version with -minimal should be installed right after libreadline, but it seems impossible to specify both.
    toolchains:
      cpeAMD-22.08:
        versions: ['0.21']
  LibTIFF:
    toolchains:
      cpeAMD-22.08:
        versions: ['4.4.0']
  libxslt:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.1.34']
  Perl:
    toolchains:
      cpeAMD-22.08:
        versions: ['5.36.0']
  intltool:
    toolchains:
      cpeAMD-22.08:
        versions: ['0.51.0']
  gdbm:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.23']
  libwebp:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.2.2']
  PROJ:
    toolchains:
      cpeAMD-22.08:
        versions: ['9.0.0']
  util-linux:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.38']
  fontconfig:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.14.0']
  GLib:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.73.0']
  libgd:
    toolchains:
      cpeAMD-22.08:
        versions: ['2.3.3']
  X11:
    toolchains:
      cpeAMD-22.08:
        versions: ['22.08']
  cairo:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.17.4']
  Tk:
    toolchains:
      cpeAMD-22.08:
        versions: ['8.6.12']
  GObject-Introspection:
    toolchains:
      cpeAMD-22.08:
        versions:
          '1.72.0':
            versionsuffix: '-cray-python3.9'
  HarfBuzz:
    toolchains:
      cpeAMD-22.08:
        versions: ['4.2.1']
  Pango:
    toolchains:
      cpeAMD-22.08:
        versions: ['1.50.7']
