software:
  ncurses:
    toolchains:
      cpeGNU-21.08:
        versions: ['6.2']
  libreadline:
    toolchains:
      cpeGNU-21.08:
        versions: ['8.1']
  gettext:
    toolchains:
      cpeGNU-21.08:
        versions:
          '0.21':
            versionsuffix: '-minimal'
