software:
  lumi-workspaces:
    toolchains:
      SYSTEM:
        versions: ['0.1']
  syslibs:
    toolchains:
      SYSTEM:
        versions: ['15.1.0']
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['21.08']
  systools:
    toolchains:
      SYSTEM:
        versions: ['15.1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['5.9']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.33.1']
