software:
  lumi-workspaces:
    toolchains:
      SYSTEM:
        versions: ['0.1']
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['21.08']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '15.1.1':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['15.1.0']
  lumi-CPEtools:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0']
      cpeGNU-21.08:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['5.9']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.3582']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.33.1']
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.3.9']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.2':
            versionsuffix: '-cray-python-3.8.5.1'
