software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['21.08']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
  Rust:
    toolchains:
      SYSTEM:
        versions: ['1.55.0']
