software:
  ncurses:
    toolchains:
      cpeCray-21.08:
        versions: ['6.2']
  libreadline:
    toolchains:
      cpeCray-21.08:
        versions: ['8.1']
  libiconv:
    toolchains:
      cpeCray-21.08:
        versions: ['1.16']
  FriBidi:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0.10']
  ICU:
    toolchains:
      cpeCray-21.08:
        versions: ['69.1']
  libunistring:
    toolchains:
      cpeCray-21.08:
        versions: ['0.9.10']
  bzip2:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0.8']
  Brotli:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0.9']
  libaec:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0.6']
  lz4:
    toolchains:
      cpeCray-21.08:
        versions: ['1.9.3']
  Szip:
    toolchains:
      cpeCray-21.08:
        versions: ['2.1.1']
  zlib:
    toolchains:
      cpeCray-21.08:
        versions: ['1.2.11']
  gzip:
    toolchains:
      cpeCray-21.08:
        versions: ['1.10']
  XZ:
    toolchains:
      cpeCray-21.08:
        versions: ['5.2.5']
  Lzip:
    toolchains:
      cpeCray-21.08:
        versions: ['1.22']
  zstd:
    toolchains:
      cpeCray-21.08:
        versions: ['1.5.0']
  libb2:
    toolchains:
      cpeCray-21.08:
        versions: ['0.98.1']
  LZO:
    toolchains:
      cpeCray-21.08:
        versions: ['2.10']
  snappy:
    toolchains:
      cpeCray-21.08:
        versions: ['1.1.8']
  Blosc:
    toolchains:
      cpeCray-21.08:
        versions: ['1.21.0']
  libdeflate:
    toolchains:
      cpeCray-21.08:
        versions: ['1.8']
  libarchive:
    toolchains:
      cpeCray-21.08:
        versions: ['3.5.1']
  giflib:
    toolchains:
      cpeCray-21.08:
        versions: ['5.2.1']
  libjpeg-turbo:
    toolchains:
      cpeCray-21.08:
        versions: ['2.1.0']
  JasPer:
    toolchains:
      cpeCray-21.08:
        versions: ['2.0.33']
  libpng:
    toolchains:
      cpeCray-21.08:
        versions: ['1.6.37']
  LibTIFF:
    toolchains:
      cpeCray-21.08:
        versions: ['4.3.0']
  libwebp:
    toolchains:
      cpeCray-21.08:
        versions: ['1.2.0']
  x264:
    toolchains:
      cpeCray-21.08:
        versions: ['20210414']
  x265:
    toolchains:
      cpeCray-21.08:
        versions: ['3.5']
  libopus:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.1']
  LAME:
    toolchains:
      cpeCray-21.08:
        versions: ['3.100']
  libogg:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.5']
  libvorbis:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.7']
  FLAC:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.3']
  libsndfile:
    toolchains:
      cpeCray-21.08:
        versions: ['1.0.31']
  libtheora:
    toolchains:
      cpeCray-21.08:
        versions: ['1.1.1']
  cURL:
    toolchains:
      cpeCray-21.08:
        versions: ['7.78.0']
  expat:
    toolchains:
      cpeCray-21.08:
        versions: ['2.4.1']
  ICU:
    toolchains:
      cpeCray-21.08:
        versions: ['69.1']
  libxml2:
    toolchains:
      cpeCray-21.08:
        versions: ['2.9.12']
  gettext: # Second entry for gettext, we may merge with the first and let EasyBuild figure out the dependencies.
    toolchains:
      cpeCray-21.08:
        versions: ['0.21']
  libxslt:
    toolchains:
      cpeCray-21.08:
        versions: ['1.1.34']
  libidn:
    toolchains:
      cpeCray-21.08:
        versions: ['1.38']
  libidn2:
    toolchains:
      cpeCray-21.08:
        versions: ['2.3.2']
  GSL:
    toolchains:
      cpeCray-21.08:
        versions: ['2.7']
  libcerf:
    toolchains:
      cpeCray-21.08:
        versions: ['1.17']
  GMP:
    toolchains:
      cpeCray-21.08:
        versions: ['6.2.1']
  MPFR:
    toolchains:
      cpeCray-21.08:
        versions: ['4.1.0']
  MPC:
    toolchains:
      cpeCray-21.08:
        versions: ['1.2.1']
  mpdecimal:
    toolchains:
      cpeCray-21.08:
        versions: ['2.5.1']
  double-conversion:
    toolchains:
      cpeCray-21.08:
        versions: ['3.1.5']
  file:
    toolchains:
      cpeCray-21.08:
        versions: ['5.40']
  gc:
    toolchains:
      cpeCray-21.08:
        versions: ['8.0.4']
  gdbm:
    toolchains:
      cpeCray-21.08:
        versions: ['1.20']
  libevent:
    toolchains:
      cpeCray-21.08:
        versions: ['2.1.12']
  libffi:
    toolchains:
      cpeCray-21.08:
        versions: ['3.4.2']
  libyaml:
    toolchains:
      cpeCray-21.08:
        versions: ['0.2.5']
  LMDB:
    toolchains:
      cpeCray-21.08:
        versions: ['0.9.29']
  PCRE:
    toolchains:
      cpeCray-21.08:
        versions: ['8.45']
  PCRE2:
    toolchains:
      cpeCray-21.08:
        versions: ['10.37']
  UDUNITS:
    toolchains:
      cpeCray-21.08:
        versions: ['2.2.28']
  util-linux:
    toolchains:
      cpeCray-21.08:
        versions: ['2.37.1']
  wget:
    toolchains:
      cpeCray-21.08:
        versions: ['1.21.1']
  pixman:
    toolchains:
      cpeCray-21.08:
        versions: ['0.40.0']
  freetype:
    toolchains:
      cpeCray-21.08:
        versions: ['2.10.4']
  fontconfig:
    toolchains:
      cpeCray-21.08:
        versions: ['2.13.94']
  DB:
    toolchains:
      cpeCray-21.08:
        versions: ['18.1.40']
  libpciaccess:
    toolchains:
      cpeCray-21.08:
        versions: ['0.16']
  termcap:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.1']
  Perl:
    toolchains:
      cpeCray-21.08:
        versions: ['5.34.0']
  intltool:
    toolchains:
      cpeCray-21.08:
        versions: ['0.51.0']
  GLib:
    toolchains:
      cpeCray-21.08:
        versions: ['2.69.1']
  X11:
    toolchains:
      cpeCray-21.08:
        versions: ['21.08']
  Tcl:
    toolchains:
      cpeCray-21.08:
        versions: ['8.6.11']
  SQLite:
    toolchains:
      cpeCray-21.08:
        versions: ['3.36.0']
  PROJ:
    toolchains:
      cpeCray-21.08:
        versions: ['8.1.1']
  libtirpc:
    toolchains:
      cpeCray-21.08:
        versions: ['1.3.2']
  libgd:
    toolchains:
      cpeCray-21.08:
        versions: ['2.3.3']
  cairo:
    toolchains:
      cpeCray-21.08:
        versions: ['1.17.4']
  GObject-Introspection:
    toolchains:
      cpeCray-21.08:
        versions:
          '1.68.0':
            versionsuffix: '-cray-python3.8'
  HarfBuzz:
    toolchains:
      cpeCray-21.08:
        versions: ['2.6.4']
  Pango:
    toolchains:
      cpeCray-21.08:
        versions: ['1.48.10']
  Boost:
    toolchains:
      cpeCray-21.08:
        versions: ['1.77.0']
  METIS:
    toolchains:
      cpeCray-21.08:
        versions: ['5.1.0']
  ParMETIS:
    toolchains:
      cpeCray-21.08:
        versions: ['4.0.3']
  SCOTCH:
    toolchains:
      cpeCray-21.08:
        versions: ['6.1.1']
  ESMF:
    toolchains:
      cpeCray-21.08:
        versions: ['8.1.1']
  gnuplot:
    toolchains:
      cpeCray-21.08:
        versions: ['5.4.2']
