software:
  METIS:
    toolchains:
      cpeGNU-21.08:
        versions: ['5.1.0']
  ParMETIS:
    toolchains:
      cpeGNU-21.08:
        versions: ['4.0.3']
  SCOTCH:
    toolchains:
      cpeGNU-21.08:
        versions: ['6.1.1']
  ESMF:
    toolchains:
      cpeGNU-21.08:
        versions: ['8.1.1']
  gnuplot:
    toolchains:
      cpeGNU-21.08:
        versions: ['5.4.2']
  ELPA:
    toolchains:
      cpeGNU-21.08:
        versions: ['2021.05.002']
  VampirServer:
    toolchains:
      cpeGNU-21.08:
        versions: ['10.0.0']
  Score-P:
    toolchains:
      cpeGNU-21.08:
        versions: ['7.1']
