software:
  METIS:
    toolchains:
      cpeCray-22.06:
        versions: ['5.1.0']
  ParMETIS:
    toolchains:
      cpeCray-22.06:
        versions: ['4.0.3']
  SCOTCH:
    toolchains:
      cpeCray-22.06:
        versions: ['6.1.3']
  ESMF:
    toolchains:
      cpeCray-22.06:
        versions: ['8.3.0']
  gnuplot:
    toolchains:
      cpeCray-22.06:
        versions: ['5.4.3']
#  VampirServer:
#    toolchains:
#      cpeCray-22.06:
#        versions: ['10.0.0']
#  Score-P:
#    toolchains:
#      cpeCray-22.06:
#        versions: ['7.1']
