software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['22.06']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '22.06':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['22.06']
  lumi-CPEtools:
    toolchains:
      SYSTEM:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.3']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.5172','9.0.0016']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.36.1']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.2']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.2':
            versionsuffix: '-cray-python-default'
#  rocm:
#    toolchains:
#      SYSTEM:
#        versions: ['4.5.2']
#  rocmlibs:
#    toolchains:
#      SYSTEM:
#        versions: ['4.5.2']
#  RCCL:
#    toolchains:
#      SYSTEM:
#        versions: ['4.5.2']
#  rocThrust:
#    toolchains:
#      SYSTEM:
#        versions: ['4.5.2']
