software:
  Blosc:
    toolchains:
      cpeCray-21.12:
        versions: ['1.21.1']
  Brotli:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0.9']
  bzip2:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0.8']
  DB:
    toolchains:
      cpeCray-21.12:
        versions: ['18.1.40']
  double-conversion:
    toolchains:
      cpeCray-21.12:
        versions: ['3.1.5']
  expat:
    toolchains:
      cpeCray-21.12:
        versions: ['2.4.6']
  FriBidi:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0.10']
  giflib:
    toolchains:
      cpeCray-21.12:
        versions: ['5.2.1']
  gc:
    toolchains:
      cpeCray-21.12:
        versions: ['8.2.0']
  GMP:
    toolchains:
      cpeCray-21.12:
        versions: ['6.2.1']
  GSL:
    toolchains:
      cpeCray-21.12:
        versions: ['2.7']
  gzip:
    toolchains:
      cpeCray-21.12:
        versions: ['1.10']
  ICU:
    toolchains:
      cpeCray-21.12:
        versions: ['69.1']
  libaec:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0.6']
  libb2:
    toolchains:
      cpeCray-21.12:
        versions: ['0.98.1']
  libcerf:
    toolchains:
      cpeCray-21.12:
        versions: ['1.17']
  libdeflate:
    toolchains:
      cpeCray-21.12:
        versions: ['1.8']
  libffi:
    toolchains:
      cpeCray-21.12:
        versions: ['3.4.2']
  libidn:
    toolchains:
      cpeCray-21.12:
        versions: ['1.38']
  libidn2:
    toolchains:
      cpeCray-21.12:
        versions: ['2.3.2']
  libjpeg-turbo:
    toolchains:
      cpeCray-21.12:
        versions: ['2.1.0']
  libogg:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.5']
  libopus:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.1']
  libtirpc:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.2']
  libyaml:
    toolchains:
      cpeCray-21.12:
        versions: ['0.2.5']
  LMDB:
    toolchains:
      cpeCray-21.12:
        versions: ['0.9.29']
  lz4:
    toolchains:
      cpeCray-21.12:
        versions: ['1.9.3']
  Lzip:
    toolchains:
      cpeCray-21.12:
        versions: ['1.23']
  LZO:
    toolchains:
      cpeCray-21.12:
        versions: ['2.10']
  mpdecimal:
    toolchains:
      cpeCray-21.12:
        versions: ['2.5.1']
  Szip:
    toolchains:
      cpeCray-21.12:
        versions: ['2.1.1']
  termcap:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.1']
  x264:
    toolchains:
      cpeCray-21.12:
        versions: ['20210613']
  x265:
    toolchains:
      cpeCray-21.12:
        versions: ['3.5']
  zlib:
    toolchains:
      cpeCray-21.12:
        versions: ['1.2.11']
  cURL:
    toolchains:
      cpeCray-21.12:
        versions: ['7.78.0']
  file:
    toolchains:
      cpeCray-21.12:
        versions: ['5.41']
  FLAC:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.3']
  JasPer:
    toolchains:
      cpeCray-21.12:
        versions: ['2.0.33']
  LAME:
    toolchains:
      cpeCray-21.12:
        versions: ['3.100']
  libevent:
    toolchains:
      cpeCray-21.12:
        versions: ['2.1.12']
  libpciaccess:
    toolchains:
      cpeCray-21.12:
        versions: ['0.16']
  libpng:
    toolchains:
      cpeCray-21.12:
        versions: ['1.6.37']
  libvorbis:
    toolchains:
      cpeCray-21.12:
        versions: ['1.3.7']
  MPFR:
    toolchains:
      cpeCray-21.12:
        versions: ['4.1.0']
  snappy:
    toolchains:
      cpeCray-21.12:
        versions: ['1.1.9']
  Tcl:
    toolchains:
      cpeCray-21.12:
        versions: ['8.6.11']
  UDUNITS:
    toolchains:
      cpeCray-21.12:
        versions: ['2.2.28']
  freetype:
    toolchains:
      cpeCray-21.12:
        versions: ['2.11.0']
  libiconv:
    toolchains:
      cpeCray-21.12:
        versions: ['1.16']
  libsndfile:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0.31']
  libtheora:
    toolchains:
      cpeCray-21.12:
        versions: ['1.1.1']
  MPC:
    toolchains:
      cpeCray-21.12:
        versions: ['1.2.1']
  PCRE:
    toolchains:
      cpeCray-21.12:
        versions: ['8.45']
  PCRE2:
    toolchains:
      cpeCray-21.12:
        versions: ['10.37']
  pixman:
    toolchains:
      cpeCray-21.12:
        versions: ['0.40.0']
  SQLite:
    toolchains:
      cpeCray-21.12:
        versions: ['3.36.0']
  XZ:
    toolchains:
      cpeCray-21.12:
        versions: ['5.2.5']
  libunistring:
    toolchains:
      cpeCray-21.12:
        versions: ['1.0']
  libxml2:
    toolchains:
      cpeCray-21.12:
        versions: ['2.9.12']
  wget:
    toolchains:
      cpeCray-21.12:
        versions: ['1.21.2']
  zstd:
    toolchains:
      cpeCray-21.12:
        versions: ['1.5.0']
  Boost:
    toolchains:
      cpeCray-21.12:
        versions: ['1.77.0']
  libarchive:
    toolchains:
      cpeCray-21.12:
        versions: ['3.5.1']
  gettext: # The version with -minimal should be installed right after libreadline, but it seems impossible to specify both.
    toolchains:
      cpeCray-21.12:
        versions: ['0.21']
  LibTIFF:
    toolchains:
      cpeCray-21.12:
        versions: ['4.3.0']
  libxslt:
    toolchains:
      cpeCray-21.12:
        versions: ['1.1.34']
  Perl:
    toolchains:
      cpeCray-21.12:
        versions: ['5.34.0']
  intltool:
    toolchains:
      cpeCray-21.12:
        versions: ['0.51.0']
  gdbm:
    toolchains:
      cpeCray-21.12:
        versions: ['1.20']
  libwebp:
    toolchains:
      cpeCray-21.12:
        versions: ['1.2.0']
  PROJ:
    toolchains:
      cpeCray-21.12:
        versions: ['8.1.1']
  util-linux:
    toolchains:
      cpeCray-21.12:
        versions: ['2.37.1']
  fontconfig:
    toolchains:
      cpeCray-21.12:
        versions: ['2.13.94']
  GLib:
    toolchains:
      cpeCray-21.12:
        versions: ['2.69.1']
  libgd:
    toolchains:
      cpeCray-21.12:
        versions: ['2.3.3']
  X11:
    toolchains:
      cpeCray-21.12:
        versions: ['21.12']
  cairo:
    toolchains:
      cpeCray-21.12:
        versions: ['1.17.4']
  Tk:
    toolchains:
      cpeCray-21.12:
        versions: ['8.6.11']
  GObject-Introspection:
    toolchains:
      cpeCray-21.12:
        versions:
          '1.71.0':
            versionsuffix: '-cray-python3.9'
  HarfBuzz:
    toolchains:
      cpeCray-21.12:
        versions: ['2.8.2']
  Pango:
    toolchains:
      cpeCray-21.12:
        versions: ['1.48.10']
