software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['21.12']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '21.12':
            versionsuffix: '-static'
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.3.9']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
