software:
  ncurses:
    toolchains:
      cpeCray-21.06:
        versions: [6.2]
      cpeGNU-21.06:
        versions: [6.2]
      cpeAMD-21.06:
        versions: [6.2]
  libreadline:
    toolchains:
      cpeCray-21.06:
        versions: [8.1]
      cpeGNU-21.06:
        versions: [8.1]
      cpeAMD-21.06:
        versions: [8.1]
  gettext:
    toolchains:
      cpeCray-21.06:
        versions:
          0.21:
            versionsuffix: '-minimal'
      cpeGNU-21.06:
        versions:
          0.21:
            versionsuffix: '-minimal'
      cpeAMD-21.06:
        versions:
          0.21:
            versionsuffix: '-minimal'
  libiconv:
    toolchains:
      cpeCray-21.06:
        versions: [1.16]
      cpeGNU-21.06:
        versions: [1.16]
      cpeAMD-21.06:
        versions: [1.16]
  FriBidi:
    toolchains:
      cpeCray-21.06:
        versions: [1.0.10]
      cpeGNU-21.06:
        versions: [1.0.10]
      cpeAMD-21.06:
        versions: [1.0.10]
  ICU:
    toolchains:
      cpeCray-21.06:
        versions: [69.1]
      cpeGNU-21.06:
        versions: [69.1]
      cpeAMD-21.06:
        versions: [69.1]
  libunistring:
    toolchains:
      cpeCray-21.06:
        versions: [0.9.10]
      cpeGNU-21.06:
        versions: [0.9.10]
      cpeAMD-21.06:
        versions: [0.9.10]
  bzip2:
    toolchains:
      cpeCray-21.06:
        versions: [1.0.8]
      cpeGNU-21.06:
        versions: [1.0.8]
      cpeAMD-21.06:
        versions: [1.0.8]
  Brotli:
    toolchains:
      cpeCray-21.06:
        versions: [1.0.9]
      cpeGNU-21.06:
        versions: [1.0.9]
      cpeAMD-21.06:
        versions: [1.0.9]
  lz4:
    toolchains:
      cpeCray-21.06:
        versions: [1.9.3]
      cpeGNU-21.06:
        versions: [1.9.3]
      cpeAMD-21.06:
        versions: [1.9.3]
  Szip:
    toolchains:
      cpeCray-21.06:
        versions: [2.1.1]
      cpeGNU-21.06:
        versions: [2.1.1]
      cpeAMD-21.06:
        versions: [2.1.1]
  zlib:
    toolchains:
      cpeCray-21.06:
        versions: [1.2.11]
      cpeGNU-21.06:
        versions: [1.2.11]
      cpeAMD-21.06:
        versions: [1.2.11]
  gzip:
    toolchains:
      cpeCray-21.06:
        versions: [1.10]
      cpeGNU-21.06:
        versions: [1.10]
      cpeAMD-21.06:
        versions: [1.10]
  XZ:
    toolchains:
      cpeCray-21.06:
        versions: [5.2.5]
      cpeGNU-21.06:
        versions: [5.2.5]
      cpeAMD-21.06:
        versions: [5.2.5]
  Lzip:
    toolchains:
      cpeCray-21.06:
        versions: [1.22]
      cpeGNU-21.06:
        versions: [1.22]
      cpeAMD-21.06:
        versions: [1.22]
  zstd:
    toolchains:
      cpeCray-21.06:
        versions: [1.5.0]
      cpeGNU-21.06:
        versions: [1.5.0]
      cpeAMD-21.06:
        versions: [1.5.0]
  libb2:
    toolchains:
      cpeCray-21.06:
        versions: [0.98.1]
      cpeGNU-21.06:
        versions: [0.98.1]
      cpeAMD-21.06:
        versions: [0.98.1]
  LZO:
    toolchains:
      cpeCray-21.06:
        versions: [2.10]
      cpeGNU-21.06:
        versions: [2.10]
      cpeAMD-21.06:
        versions: [2.10]
  snappy:
    toolchains:
      cpeCray-21.06:
        versions: [1.1.8]
      cpeGNU-21.06:
        versions: [1.1.8]
      cpeAMD-21.06:
        versions: [1.1.8]
  Blosc:
    toolchains:
      cpeCray-21.06:
        versions: [1.21.0]
      cpeGNU-21.06:
        versions: [1.21.0]
      cpeAMD-21.06:
        versions: [1.21.0]
  libdeflate:
    toolchains:
      cpeCray-21.06:
        versions: [1.8]
      cpeGNU-21.06:
        versions: [1.8]
      cpeAMD-21.06:
        versions: [1.8]
  libarchive:
    toolchains:
      cpeCray-21.06:
        versions: [3.5.1]
      cpeGNU-21.06:
        versions: [3.5.1]
      cpeAMD-21.06:
        versions: [3.5.1]
  giflib:
    toolchains:
      cpeCray-21.06:
        versions: [5.2.1]
      cpeGNU-21.06:
        versions: [5.2.1]
      cpeAMD-21.06:
        versions: [5.2.1]
  libjpeg-turbo:
    toolchains:
      cpeCray-21.06:
        versions: [2.1.0]
      cpeGNU-21.06:
        versions: [2.1.0]
      cpeAMD-21.06:
        versions: [2.1.0]
  JasPer:
    toolchains:
      cpeCray-21.06:
        versions: [2.0.33]
      cpeGNU-21.06:
        versions: [2.0.33]
      cpeAMD-21.06:
        versions: [2.0.33]
  libpng:
    toolchains:
      cpeCray-21.06:
        versions: [1.6.37]
      cpeGNU-21.06:
        versions: [1.6.37]
      cpeAMD-21.06:
        versions: [1.6.37]
  LibTIFF:
    toolchains:
      cpeCray-21.06:
        versions: [4.3.0]
      cpeGNU-21.06:
        versions: [4.3.0]
      cpeAMD-21.06:
        versions: [4.3.0]
  libwebp:
    toolchains:
      cpeCray-21.06:
        versions: [1.2.0]
      cpeGNU-21.06:
        versions: [1.2.0]
      cpeAMD-21.06:
        versions: [1.2.0]
  x264:
    toolchains:
      cpeCray-21.06:
        versions: [20210414]
      cpeGNU-21.06:
        versions: [20210414]
      cpeAMD-21.06:
        versions: [20210414]
  x265:
    toolchains:
      cpeCray-21.06:
        versions: [3.5]
      cpeGNU-21.06:
        versions: [3.5]
      cpeAMD-21.06:
        versions: [3.5]
  libopus:
    toolchains:
      cpeCray-21.06:
        versions: [1.3.1]
      cpeGNU-21.06:
        versions: [1.3.1]
      cpeAMD-21.06:
        versions: [1.3.1]
  LAME:
    toolchains:
      cpeCray-21.06:
        versions: [3.100]
      cpeGNU-21.06:
        versions: [3.100]
      cpeAMD-21.06:
        versions: [3.100]
  libogg:
    toolchains:
      cpeCray-21.06:
        versions: [1.3.5]
      cpeGNU-21.06:
        versions: [1.3.5]
      cpeAMD-21.06:
        versions: [1.3.5]
  libvorbis:
    toolchains:
      cpeCray-21.06:
        versions: [1.3.7]
      cpeGNU-21.06:
        versions: [1.3.7]
      cpeAMD-21.06:
        versions: [1.3.7]
  FLAC:
    toolchains:
      cpeCray-21.06:
        versions: [1.3.3]
      cpeGNU-21.06:
        versions: [1.3.3]
      cpeAMD-21.06:
        versions: [1.3.3]
  libsndfile:
    toolchains:
      cpeCray-21.06:
        versions: [1.0.31]
      cpeGNU-21.06:
        versions: [1.0.31]
      cpeAMD-21.06:
        versions: [1.0.31]
  libtheora:
    toolchains:
      cpeCray-21.06:
        versions: [1.1.1]
      cpeGNU-21.06:
        versions: [1.1.1]
      cpeAMD-21.06:
        versions: [1.1.1]
  cURL:
    toolchains:
      cpeCray-21.06:
        versions: [7.78.0]
      cpeGNU-21.06:
        versions: [7.78.0]
      cpeAMD-21.06:
        versions: [7.78.0]
  expat:
    toolchains:
      cpeCray-21.06:
        versions: [2.4.1]
      cpeGNU-21.06:
        versions: [2.4.1]
      cpeAMD-21.06:
        versions: [2.4.1]
  libxml2:
    toolchains:
      cpeCray-21.06:
        versions: [2.9.12]
      cpeGNU-21.06:
        versions: [2.9.12]
      cpeAMD-21.06:
        versions: [2.9.12]
  libxslt:
    toolchains:
      cpeCray-21.06:
        versions: [1.1.34]
      cpeGNU-21.06:
        versions: [1.1.34]
      cpeAMD-21.06:
        versions: [1.1.34]
  libidn:
    toolchains:
      cpeCray-21.06:
        versions: [1.38]
      cpeGNU-21.06:
        versions: [1.38]
      cpeAMD-21.06:
        versions: [1.38]
  libidn2:
    toolchains:
      cpeCray-21.06:
        versions: [2.3.2]
      cpeGNU-21.06:
        versions: [2.3.2]
      cpeAMD-21.06:
        versions: [2.3.2]
  GMP:
    toolchains:
      cpeCray-21.06:
        versions: [6.2.1]
      cpeGNU-21.06:
        versions: [6.2.1]
      cpeAMD-21.06:
        versions: [6.2.1]
