software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: [21.06]
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: [1.19.3]
  Rust:
    toolchains:
      SYSTEM:
        versions: [1.54.0]
