software:
  ncurses:
    toolchains:
      cpeCray-21.06:
        versions: [6.2]
      cpeGNU-21.06:
        versions: [6.2]
      cpeAMD-21.06:
        versions: [6.2]
  libreadline:
    toolchains:
      cpeCray-21.06:
        versions: [8.1]
      cpeGNU-21.06:
        versions: [8.1]
      cpeAMD-21.06:
        versions: [8.1]
  GMP:
    toolchains:
      cpeCray-21.06:
        versions: [6.2.1]
      cpeGNU-21.06:
        versions: [6.2.1]
      cpeAMD-21.06:
        versions: [6.2.1]
