software:
  ELPA:
    toolchains:
      cpeGNU-21.12:
        versions: ['2021.11.001']
  METIS:
    toolchains:
      cpeGNU-21.12:
        versions: ['5.1.0']
  ParMETIS:
    toolchains:
      cpeGNU-21.12:
        versions: ['4.0.3']
  SCOTCH:
    toolchains:
      cpeGNU-21.12:
        versions: ['6.1.3']
  ESMF:
    toolchains:
      cpeGNU-21.12:
        versions: ['8.2.0']
  gnuplot:
    toolchains:
      cpeGNU-21.12:
        versions: ['5.4.3']
  VampirServer:
    toolchains:
      cpeGNU-21.12:
        versions: ['10.0.0']
  Score-P:
    toolchains:
      cpeGNU-21.12:
        versions: ['7.1']
