software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['22.05']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '22.05':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['22.05']
  lumi-CPEtools:
    toolchains:
      cpeAOCC-22.05:
        versions: ['1.0']
      cpeCray-22.05:
        versions: ['1.0']
      cpeGNU-22.05:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.3']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.5055']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.36.1']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.2']
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.4']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.2':
            versionsuffix: '-cray-python-3.9.12.1'
#  Rust:
#    toolchains:
#      SYSTEM:
#        versions: ['1.61.0']

